# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-ast
        name: python check ast
    -   id: trailing-whitespace
        name: trim trailing whitespace
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
    -   id: end-of-file-fixer
        name: end of line fixer
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
    -   id: check-merge-conflict
        name: check merge conflicts
# -   repo: local
#     hooks:
#     -   id: print-checker
#         name: print checker
#         description: Check python files for print statements
#         entry: python scripts/print_checker.py
#         files: .*\.py$
#         exclude: ^scripts\/.*\.py$
#         language: python
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: (.*\.py$)
        exclude: ^(.*\/migrations\/.*\.py|.*\.cfg$)$
        language: python

# -   repo: https://github.com/PyCQA/bandit
#     rev: '1.7.4'
#     hooks:
#     - id: bandit
#       name: bandit
#       language_version: python
#       exclude: ^(.*/test/.*|.*/tests/.*|.*/test\.py|.*/tests\.py|.*\.cfg$)$
#       args:
#           - --config=.bandit.yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      exclude: ^src/settings/environments/
      args:
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
