version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 classes-contenclat/ss_2022_04_08_deployments/src/example_module.py

  test:
    working_directory: ~/circleci-python
    docker:
      # - image: "circleci/python:3.6.4"
      - image: "cimg/python:3.9.6"
    steps:
      - checkout
      - run: |
          pip3 install pytest --upgrade --user
          pytest classes-content/class_2022_04_08_deployments/tests

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
            