version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 classes-content/2022-04-08-deployments/example_module.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: |
          pip3 install pytest --upgrade --user
          pytest classes-content/2022-04-08-deployments/ tests


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
